### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by ghost** [amokjs/amok#193]
Hello. I'm doing the steps from the guides (from github) and videos to use amok and it gives me the following error:

``` bash
events.js:154
      throw er; // Unhandled 'error' event
      ^

TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:90:11)
    at Object.urlParse [as parse] (url.js:84:5)
    at WebSocket.initAsClient (/usr/lib/node_modules/amok/node_modules/ws/lib/WebSocket.js:550:23)
    at new WebSocket (/usr/lib/node_modules/amok/node_modules/ws/lib/WebSocket.js:74:18)
    at Function.connect (/usr/lib/node_modules/amok/node_modules/ws/index.js:42:16)
    at Client.connect (/usr/lib/node_modules/amok/node_modules/rdbg/lib/index.js:220:19)
    at /usr/lib/node_modules/amok/lib/index.js:67:14
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/amok/node_modules/rdbg/lib/index.js:328:16)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
```

The steps to reproduce the errors under GNU/Linux with chromium are the following:

``` bash
# first ensure that there is nothing causing interference
killall chromium
echo "alert('working');" > index.js
# open chromium with debug port, wait until is open and excecute amok
chromium --remote-debugging-port=9223 &
amok index.js
```

**OS:** ArchLinux
**Browser:** Chromium v49.0.2623.87
**Node:** v5.5.0
**Amok:** v1.1.3

**Comment by caspervonb** [comment]
It's not a bug per-se, just bad error handling and early return when there's no connection available (https://github.com/amokjs/amok/blob/v1.1.4/lib/index.js#L63-L67)

Try giving chromium a chance to spin up.

```js
$ chromium --remote-debugging-port=9223 & (sleep 5 && amok index.js)
```

**Comment by yetatore** [comment]
Sorry, I was unclear in the bug report... I manually waited chromium to be open.
Running the given command raises the same error (the first output is from chromium):
```
$ chromium --remote-debugging-port=9223 & (sleep 5 && amok index.js)
[1] 1089
[1089:1089:0415/101300:ERROR:logging.h(813)] Failed to call method: org.freedesktop.DBus.ObjectManager.GetManagedObjects: object_path= /: org.freedesktop.DBus.Error.ServiceUnknown: The name org.bluez was not provided by any .service files
[1089:1089:0415/101300:ERROR:logging.h(813)] Failed to call method: org.freedesktop.DBus.ObjectManager.GetManagedObjects: object_path= /: org.freedesktop.DBus.Error.ServiceUnknown: The name org.bluez was not provided by any .service files
events.js:154
      throw er; // Unhandled 'error' event
      ^

TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:90:11)
    at Object.urlParse [as parse] (url.js:84:5)
    at WebSocket.initAsClient (/usr/lib/node_modules/amok/node_modules/ws/lib/WebSocket.js:550:23)
    at new WebSocket (/usr/lib/node_modules/amok/node_modules/ws/lib/WebSocket.js:74:18)
    at Function.connect (/usr/lib/node_modules/amok/node_modules/ws/index.js:42:16)
    at Client.connect (/usr/lib/node_modules/amok/node_modules/rdbg/lib/index.js:220:19)
    at /usr/lib/node_modules/amok/lib/index.js:67:14
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/amok/node_modules/rdbg/lib/index.js:328:16)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
```

Thanks for the kick answer eitherways ;)

**Comment by caspervonb** [comment]
Hmph.. embedded devtools open?

**Comment by yetatore** [comment]
Mmm... What's that?

**Comment by yetatore** [comment]
If it helps, I cloned amok 1.1.4 and the tests fails:
```
$ npm test
> amok@1.1.4 test /home/yetatore/work/amok
> make test

tape test/lib.js test/lib_print.js test/bin_watch.js test/lib_compiler.js test/lib_hotpatch.js test/lib_hotpatch_compiler.js test/bin.js test/bin_hotpatch.js test/bin_hotpatch_compiler.js test/lib_server.js test/lib_browser.js test/lib_watch.js
TAP version 13
# run plugins
ok 1 (unnamed assert)
ok 2 (unnamed assert)
ok 3 null
ok 4 (unnamed assert)
# open print url in chrome
not ok 5 plan != count
  ---
    operator: fail
    expected: 3
    actual:   0
  ...

[other fails omited for clarity]
```

**Comment by yetatore** [comment]
Result of localhost:9223/json/list:
``` json
[ {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:9223/devtools/page/78047DD6-4081-4DE9-BA35-CBE043EF7B7C",
   "faviconUrl": "https://www.google.com.uy/favicon.ico",
   "id": "78047DD6-4081-4DE9-BA35-CBE043EF7B7C",
   "title": "New Tab",
   "type": "page",
   "url": "http://localhost:9223/json/list",
   "webSocketDebuggerUrl": "ws://localhost:9223/devtools/page/78047DD6-4081-4DE9-BA35-CBE043EF7B7C"
}, {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:9223/devtools/page/A5630855-EADB-41BA-889A-741B3E7440AD",
   "id": "A5630855-EADB-41BA-889A-741B3E7440AD",
   "title": "Worker pid:4014",
   "type": "service_worker",
   "url": "https://www.google.com.uy/_/chrome/newtab-serviceworker.js",
   "webSocketDebuggerUrl": "ws://localhost:9223/devtools/page/A5630855-EADB-41BA-889A-741B3E7440AD"
} ]
```

You also want the html file of http://localhost:9223?

**Comment by yetatore** [comment]
If it helps tests are failing:
``` bash
$ npm test

> amok@1.1.4 test /home/yetatore/work/amok
> make test

tape test/lib.js test/lib_print.js test/bin_watch.js test/lib_compiler.js test/lib_hotpatch.js test/lib_hotpatch_compiler.js test/bin.js test/bin_hotpatch.js test/bin_hotpatch_compiler.js test/lib_server.js test/lib_browser.js test/lib_watch.js
TAP version 13
# run plugins
ok 1 (unnamed assert)
ok 2 (unnamed assert)
ok 3 null
ok 4 (unnamed assert)
# open url in chrome
not ok 5 plan != count
  ---
    operator: fail
    expected: 3
    actual:   0
  ...
```
I ommited the rest of the errors that only says:
```
not ok <NUMBER> test exited without ending
  ---
    operator: fail
  ...
```

**Comment by yetatore** [comment]
Any sugestion?

**Comment by caspervonb** [comment]
Not entirely sure what's going on here, I think this is ending up being undefined https://github.com/amokjs/amok/blob/v1.1.4/lib/index.js#L63-L65

Using the `--browser` option, still running into issues? (It overrides and retries)
